
[colors.primary]
foreground = "0xdddddd"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.normal]
family = "SauceCodePro Nerd Font Mono"

[selection]
save_to_clipboard = true

[general]
import = ["/home/svenr/.config/alacritty/themes/themes/citylights.toml"]
